updated assemble script

diff --git a/s2i-scripts/.s2i/bin/assemble b/s2i-scripts/.s2i/bin/assemble
--- a/s2i-scripts/.s2i/bin/assemble
+++ b/s2i-scripts/.s2i/bin/assemble
@@ -1,15 +1,8 @@
 #!/bin/bash
 
-set -e
 
-source ${HTTPD_CONTAINER_SCRIPTS_PATH}/common.sh
-
-echo "---> Enabling s2i support in httpd24 image"
-
-config_s2i
-
-######## CUSTOMIZATION STARTS HERE ############
-
+function createPage(){
+	
 echo "---> Installing application source"
 cp -Rf /tmp/src/*.html ./
 
@@ -17,25 +10,23 @@ DATE=`date "+%b %d, %Y @ %H:%M %p"`
 
 echo "---> Creating info page"
 echo "Page built on $DATE" >> ./info.html
+echo "Page proudly built by $(whoami)" >> ./info.html 
 echo "Proudly served by Apache HTTP Server version $HTTPD_VERSION" >> ./info.html
 
-######## CUSTOMIZATION ENDS HERE ############
+}
 
-if [ -d ./httpd-cfg ]; then
-  echo "---> Copying httpd configuration files..."
-  if [ "$(ls -A ./httpd-cfg/*.conf)" ]; then
-    cp -v ./httpd-cfg/*.conf "${HTTPD_CONFIGURATION_PATH}"
-    rm -rf ./httpd-cfg
-  fi
+echo "Making pre-invocation changes...."
+
+/usr/libexec/s2i/assemble
+rc=$?
+
+if [ $ rc -eq 0 ]; then
+	echo "Making post-invocation changes....."
+	createPage()
+
 else
-  if [ -d ./cfg ]; then
-    echo "---> Copying httpd configuration files from deprecated './cfg' directory, use './httpd-cfg' instead..."
-    if [ "$(ls -A ./cfg/*.conf)" ]; then
-      cp -v ./cfg/*.conf "${HTTPD_CONFIGURATION_PATH}"
-      rm -rf ./cfg
-    fi
-  fi
+	echo "Error: assembly falied!"
+
 fi
 
-# Fix source directory permissions
-fix-permissions ./
+exit $rc
